In [3]:
import tensorflow as tf
import os

In [4]:
def read_train_sets(train_path, validation_size):
    IMAGE_FILE_PATH = train_path
    filenames = [ os.path.join( IMAGE_FILE_PATH, filename ) for filename in os.listdir( IMAGE_FILE_PATH ) ]
    filename_queue = tf.train.string_input_producer( filenames )

    image_reader = tf.WholeFileReader()
    
    _, image_file = image_reader.read(filename_queue)
    
    image = tf.image.decode_jpeg(image_file)
    
    image_orig = tf.image.decode_jpeg(image_file)
    image = tf.image.resize_images(image_orig, [224, 224])
    image.set_shape((224, 224, 3))
    batch_size = 50
    num_preprocess_threads = 1
    min_queue_examples = 256
    # min_queue_examples = 600
    images = tf.train.shuffle_batch(
    [image],
    batch_size=batch_size,
    num_threads=num_preprocess_threads,
    capacity=min_queue_examples + 3 * batch_size,
    min_after_dequeue=min_queue_examples)

    with tf.Session() as sess:
        # Required to get the filename matching to run.
        tf.global_variables_initializer().run()    # Coordinate the loading of image files.
        coord = tf.train.Coordinator()
        threads = tf.train.start_queue_runners(coord=coord)

        # Get an image tensor and print its value.
        image_tensor = sess.run(image)
        print(image_tensor)

        # Finish off the filename queue coordinator.
        coord.request_stop()
        coord.join(threads)
        

In [18]:
read_train_sets(train_path='/home/shuayb/wiki_crop/00', validation_size=0.2)

INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Shape mismatch in tuple component 0. Expected [224,224,3], got [224,224,1]
	 [[Node: shuffle_batch_1/random_shuffle_queue_enqueue = QueueEnqueueV2[Tcomponents=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](shuffle_batch_1/random_shuffle_queue, resize_images_1/Squeeze)]]
[[[255.       255.       255.      ]
  [250.60715  250.60715  250.60715 ]
  [232.2857   232.2857   232.2857  ]
  ...
  [ 79.23216   79.23216   79.23216 ]
  [ 84.214325  84.214325  84.214325]
  [ 87.        87.        87.      ]]

 [[254.27232  254.27232  254.27232 ]
  [252.54329  252.54329  252.54329 ]
  [236.54782  236.54782  236.54782 ]
  ...
  [ 74.28135   74.28135   74.28135 ]
  [ 79.120575  79.120575  79.120575]
  [ 81.90625   81.90625   81.90625 ]]

 [[248.53572  248.53572  248.53572 ]
  [252.47098  252.47098  252.47098 ]
  [241.16772  241.16772  241.16772 ]
  .

InvalidArgumentError: Shape mismatch in tuple component 0. Expected [224,224,3], got [224,224,1]
	 [[Node: shuffle_batch_1/random_shuffle_queue_enqueue = QueueEnqueueV2[Tcomponents=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](shuffle_batch_1/random_shuffle_queue, resize_images_1/Squeeze)]]

In [5]:
# # filename_queue = tf.train.string_input_producer(
# # tf.train.match_filenames_once("/home/shuayb/wiki_crop/00"))

# IMAGE_FILE_PATH = '/home/shuayb/wiki_crop/00'
# filenames = [ os.path.join( IMAGE_FILE_PATH, filename ) for filename in os.listdir( IMAGE_FILE_PATH ) ]
# filename_queue = tf.train.string_input_producer( filenames )

# filename_queue = tf.train.string_input_producer(['/home/shuayb/wiki_crop/00/'])

In [6]:
# image_reader = tf.WholeFileReader()

In [7]:
# _, image_file = image_reader.read(filename_queue)

In [8]:
# image = tf.image.decode_jpeg(image_file)

In [9]:
# image_orig = tf.image.decode_jpeg(image_file)
# image = tf.image.resize_images(image_orig, [224, 224])
# image.set_shape((224, 224, 3))
# batch_size = 50
# num_preprocess_threads = 1
# min_queue_examples = 256
# # min_queue_examples = 600
# images = tf.train.shuffle_batch(
# [image],
# batch_size=batch_size,
# num_threads=num_preprocess_threads,
# capacity=min_queue_examples + 3 * batch_size,
# min_after_dequeue=min_queue_examples)

In [10]:

# with tf.Session() as sess:
#     # Required to get the filename matching to run.
#     tf.global_variables_initializer().run()    # Coordinate the loading of image files.
#     coord = tf.train.Coordinator()
#     threads = tf.train.start_queue_runners(coord=coord)

#     # Get an image tensor and print its value.
#     image_tensor = sess.run(image)
#     print(image_tensor)

#     # Finish off the filename queue coordinator.
#     coord.request_stop()
#     coord.join(threads)

In [11]:
a = tf.truncated_normal([600,224,224,3])
sess = tf.Session()
sess.run(tf.global_variables_initializer())
sess.run(tf.shape(a))

array([600, 224, 224,   3], dtype=int32)

In [12]:
b=tf.reshape(a,[600,150528])
sess.run(tf.shape(b))

array([   600, 150528], dtype=int32)

In [13]:
classes = ['male', 'female']
num_classes = len(classes)
 
train_path ='/home/shuayb/wiki_crop/00'
 
# validation split
validation_size = 0.2
 
# batch size
batch_size = 600
 
data = read_train_sets(train_path, validation_size=validation_size)



[[[18.          4.          1.        ]
  [18.          4.          1.        ]
  [18.          4.          1.        ]
  ...
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]]

 [[15.044643    2.4776785   0.        ]
  [15.044643    2.4776785   0.        ]
  [15.044643    2.4776785   0.        ]
  ...
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]]

 [[14.955357    3.955357    0.        ]
  [14.955357    3.955357    0.        ]
  [14.955357    3.955357    0.        ]
  ...
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]]

 ...

 [[ 0.          0.          0.        ]
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]
  ...
  [ 2.          2.6249452   0.        ]
  [ 0.84675467  1.8660889   0.        ]
  [ 0.43304443  1.8660889   0.        ]]

 [

In [19]:
def create_weights(shape):
    return tf.Variable(tf.truncated_normal(shape, stddev=0.05))
 
def create_biases(size):
    return tf.Variable(tf.constant(0.05, shape=[size]))

In [20]:
# http://cv-tricks.com/tensorflow-tutorial/training-convolutional-neural-network-for-image-classification/
# https://gist.github.com/eerwitt/518b0c9564e500b4b50f
# https://www.datacamp.com/community/tutorials/tensorflow-tutorial